export const REQUEST_SIGNIN = 'REQUEST_SIGNIN';
export const SUCCESS_SIGNIN = 'SUCCESS_SIGNIN';
export const FAILURE_SIGNIN = 'FAILURE_SIGNIN';

export const REQUEST_SIGNUP = 'REQUEST_SIGNUP';
export const SUCCESS_SIGNUP = 'SUCCESS_SIGNUP';
export const FAILURE_SIGNUP = 'FAILURE_SIGNUP';

export const REQUEST_ADD_ACCOUNT_TYPE = 'REQUEST_ADD_ACCOUNT_TYPE';
export const SUCCESS_ADD_ACCOUNT_TYPE = 'SUCCESS_ADD_ACCOUNT_TYPE';
export const FAILURE_ADD_ACCOUNT_TYPE = 'FAILURE_ADD_ACCOUNT_TYPE';

export const REQUEST_UPDATE_COMPANY_INFO = 'REQUEST_UPDATE_COMPANY_INFO';
export const SUCCESS_UPDATE_COMPANY_INFO = 'SUCCESS_UPDATE_COMPANY_INFO';
export const FAILURE_UPDATE_COMPANY_INFO = 'FAILURE_UPDATE_COMPANY_INFO';

export const REQUEST_USER_ACCOUNT_TYPE = 'REQUEST_USER_ACCOUNT_TYPE';
export const SUCCESS_USER_ACCOUNT_TYPE = 'SUCCESS_USER_ACCOUNT_TYPE';
export const FAILURE_USER_ACCOUNT_TYPE = 'FAILURE_USER_ACCOUNT_TYPE';

export const CLEAR_ERROR_MESSAGE = 'CLEAR_ERROR_MESSAGE';
export const LOGOUT = 'LOGOUT';
